name=TouchModule
version=0.2.0
author=Pooria
maintainer=Pooria
sentence=Touch subdevice library for HDL-Buspro-style RS485 bus (STM32duino/Arduino).
paragraph=
category=Communication
url=
architectures=*
includes=TouchModule.h
depends=BusproCore, MemoryCore